nome=str(input("digite seu nome "))
print("analisando o seu nome...")
print("seu nome e maluscula e {}".format(nome.upper()))
print("seu nome e minuscula e {}".format(nome.lower()))
print("seu nome tem ao todo {} letras ".format(len(nome))